version: '2'
services:
    pimon:
        build: .
        container_name: libpimon
        image: clambin/pimon:latest
        command: --sys /host/sys
        volumes:
            - /sys:/host/sys:ro
        ports:
            - 8080:8080/tcp
        devices:
            - /dev/gpiomem:/dev/gpiomem

