version: '2'
services:
    pimon:
        build: .
        container_name: pimon
        image: clambin/pimon
        command: --sys /host/sys --debug
        volumes:
            - /sys:/host/sys:ro
        ports:
            - 8080:8080/tcp
        devices:
            - /dev/gpiomem:/dev/gpiomem

