version: '2'
services:
    pimon:
        build: .
        image: clambin/pimon:dev
        container_name: pimon.new
        volumes:
            - /sys:/host/sys:ro
        ports:
            - "8080:8080/tcp"
        devices:
            - "/dev/gpiomem:/dev/gpiomem"

