{
 "title": "Media Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "On Calendar",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mediaserver_calendar_count{job=\"pimon\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Download Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mediaserver_queued_count{job=\"pimon\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Monitoring",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "mediaserver_monitored_count{job=\"pimon\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Transmission Network Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mediaserver_download_speed{job=\"pimon\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "mediaserver_upload_speed{job=\"pimon\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Torrents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mediaserver_active_torrent_count{job=\"pimon\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "mediaserver_paused_torrent_count{job=\"pimon\"}",
     "legendFormat": "Paused"
    }
   ]
  },
  {
   "title": "Not monitored",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "expr": "mediaserver_unmonitored_count{job=\"pimon\"}",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}