{
 "title": "WatchTower",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Free on rootfs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{fstype=\"ext4\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{fstype=\"ext4\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "100-(sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"})))"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "pimon_temperature{instance=~\"pimon:8080\"}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "1-(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\", device!=\"docker0\", device!~\"^veth.*\", device!~\"^br-.*\"}[1m])  ",
     "legendFormat": "In: {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\", device!=\"docker0\", device!~\"^veth.*\", device!~\"^br-.*\"}[1m])  ",
     "legendFormat": "Out: {{device}}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "pimon_temperature", "legendFormat": "Temperature (ºC)" },
    { "expr": "pimon_fan  ", "legendFormat": "Fan status" }
   ]
  },
  { "title": "Media Library", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "OpenVPN Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(openvpn_client_tcp_udp_read_bytes_total[1m])  ",
     "legendFormat": "In"
    },
    {
     "expr": "rate(openvpn_client_tcp_udp_write_bytes_total[1m])    ",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Torrents",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mediaserver_calendar_count", "legendFormat": "{{server}}" },
    {
     "expr": "mediaserver_paused_torrent_count",
     "legendFormat": "Paused"
    },
    {
     "expr": "mediaserver_active_torrent_count",
     "legendFormat": "Active"
    }
   ]
  }
 ]
}